### ISSUE TITLE
Plugin appears nonfunctioning

### ISSUE THREAD

**Issue by cohml** [joshskidmore/zsh-fzf-history-search#31] opened 2023-06-27 02:44 UTC
MacOS Ventura 13.4

Package versions:

```shell
❯ zsh --version
zsh 5.9 (x86_64-apple-darwin22.0)
❯ fzf --version
0.41.1 (brew)
```

Cloned your master branch today and tested it with the following plugin configurations in `.zshrc`:

```shell
plugins=(
  git
  macos
  z
  zsh-autocomplete
  zsh-autosuggestions
  zsh-fzf-history-search
  zsh-syntax-highlighting
)
```

```shell
plugins=(
  git
  macos
  z
  zsh-autocomplete
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh-fzf-history-search
)
```

With the above settings, `fzf`'s `CTRL-R` output remained in the default format, with the command counter/ID instead of with date and time as described in your README:

```shell
 1965  zsh --version
 1966  fzf --version
2/1000 +S -----------------------------------------------------------------------------------------------------------
> ^zsh | ^fzf --version$
```

Let me know if you're un/able to reproduce.

**Comment by joshskidmore** [comment] 2023-06-27 12:56
Which zsh plugin manager are you using?

**Comment by cohml** [comment] 2023-06-27 15:27
I just installed it manually using the instructions [here](https://github.com/joshskidmore/zsh-fzf-history-search#oh-my-zsh) for Oh-My-Zsh.

**Comment by jordancurve** [comment] 2023-10-29 17:55
Same issue here. I'm using oh-my-zsh, which I just installed so I could try out zsh-fzf-history-search. Here's the plugins line in my .zshrc:

```
plugins=(zsh-fzf-history-search)
 ```

**Comment by dominikduda** [comment] 2023-11-02 09:29
Same for me.

**Comment by manutepowa** [comment] 2023-12-08 05:53
Same issue.

If I manually execute"source $ZSH_CUSTOM/plugins/zsh-fzf-history-search/zsh-fzf-history-search.plugin.zsh" after load .zshrc works.
But I put this line at the end of .zshrc file and not works

**Comment by joshskidmore** [comment] 2023-12-08 22:50
> u/joshskidmore Do you think you will get around to patching the OMZ sourcing failure and overriding of fzf variables?

Sorry about the delay. I will take a look at this over the weekend. Because I don't use OMZ, I'm not sure how to resolve this quickly without setting up an environment.

**Comment by manutepowa** [comment] 2023-12-10 07:47
In my case I solved it by removing the zsh-vi-mode plugin.
Instead I use vi-mode.

I don't understand why but it works

**Comment by joshskidmore** [comment] 2023-12-14 00:17
I just installed oh-my-zsh on my Macbook Pro. I did these steps:

1. Install OMZ: `sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`
2. `cd ~/.oh-my-zsh/plugins`
3. `git clone https://github.com/joshskidmore/zsh-fzf-history-search`
4. Edit ~/.zshrc and appended `zsh-fzf-history-search` to the plugins=()
5. Opened a new terminal

Using these steps, Ctrl-r works as it does in Zinit - the fzf line format is "[#] [DATE/TIME] [CMD]". Can confirm this was definitely OMZ because my prompt was different than what I use with Zinit.

**Comment by joshskidmore** [comment] 2023-12-14 01:30
In thinking about this, one suggestion might be to include `zsh-fzf-history-search` at the bottom of the `plugins=()` list. Without knowing everyone's specific scenarios and plugin lists, my assumption is if `zsh-fzf-history-search` is sourced before another plugin (or if this plugin is included in the `plugins=()` list before other plugins), other plugins might be hijacking the Ctrl-R key which could be causing a variety of issues.

**Comment by jonathanmorris180** [comment] 2024-01-12 23:22
@joshskidmore Thanks for this great plugin! For anyone experiencing issues with this while using `zsh-vi-mode`, you can fix conflicts with this:

```bash
source_if_exists () {
    if test -r "$1"; then
        source "$1"
    fi
}

# see issue: https://github.com/jeffreytse/zsh-vi-mode/issues/4
function after_init() {
    source_if_exists ~/.fzf.zsh
    source_if_exists $ZSH_CUSTOM/plugins/zsh-fzf-history-search/zsh-fzf-history-search.plugin.zsh
}
zvm_after_init_commands+=(after_init)
```

**Comment by joshskidmore** [comment] 2024-01-13 15:34
@jonathanmorris180 Thanks for the update and solution. As much as I wish this plugin could help "solve" this issue, I think that these keybinding type conflicts probably need to be resolved in individual configs and not the plugin. I'm unsure of what vim-mode behavior is bound to Ctrl-R, but I think it might be a bit presumptuous for this plugin to overwrite its keybinding.

I'm definitely up for suggestions or solutions though. Maybe this is the expected behavior?

**Comment by jonathanmorris180** [comment] 2024-01-13 21:54
@joshskidmore No problem. I agree that this would be out of the scope of your plugin. Might suffice to just add a note in the readme about the possibility of conflicts with vim plugins?

**Comment by vietvudanh** [comment] 2024-02-29 08:38
I do not use `zsh-vi-mode` at all and still have this problem. I had tried to disabled all other plugins except for just `zsh-fzf-history-search` but still not works. Looks like OMZ has problem with init the shell.
My workaround was to add this in ~/.zshrc
```shell
source $ZSH_CUSTOM/plugins/zsh-fzf-history-search/zsh-fzf-history-search.plugin.zsh
```

**Closed** 2024-05-15 21:42 UTC

**Comment by acohen716** [comment] 2024-08-15 10:24
For me it was the order of these lines that caused the issue in my `~/.zshrc`:

Fails:
```
...
[ -f $ZSH/oh-my-zsh.sh ] && source $ZSH/oh-my-zsh.sh
...
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
...
```

Succeeds:
```
...
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
...
[ -f $ZSH/oh-my-zsh.sh ] && source $ZSH/oh-my-zsh.sh
...
```

I hope this helps someone else too.
